### ISSUE TITLE
Add JS tests

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/global-nav#5]
We should have full unit tests for the function in the JS.

**Comment by richmccartney** [comment]
@anthonydillon https://github.com/jasmine/gulp-jasmine-browser <- could look at using this.

**Comment by tbille** [comment]
@anthonydillon do we have some now?

**Comment by steverydz** [comment]
@tbille as far as I can tell there aren't any right now.

I think it would be a good idea to establish what it is specifically that we want to test.

Testing the DOM is tricky. It's possible to mock it in tools like jest but I never feel comfortable with that. It's way too easy to write tests that are false positives because they are testing the mocks rather than the actual code.

**Comment by pmahnke** [comment]
@anthonydillon @steverydz we appear to have tests now, closing

**Comment by anthonydillon** [comment]
I don't see any tests yet. Would like to see some.

**Comment by anasereijo** [comment]
@anthonydillon this issue was opened 5 years ago. Is it still relevant?

**Comment by petesfrench** [comment]
@sowasred2012 if we are ousting the global-nav, can we close this?

**Comment by sowasred2012** [comment]
@petesfrench I think we can. 

For context/posterity - we are currently updating the the top nav such that the products dropdown the global nav provides will become part of each site's main navigation, rather than a separate element, and the global nav has never (to my knowledge, at least) released an update that was broken or that broke the site it was included in, so there's not much to be gained from adding tests to the project.
